name: Go Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.3'

      - name: Go get main
        run: go get main

      - name: Build
        run: go build .

      - name: Exec
        run: ./main.exe

      - name: Test
        run: go test -v ./main.go ./api.go ./server.go ./main_test.go
